dw_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres_dw
      port: 5432
      user: postgres
      password: postgres
      dbname: postgres
      schema: public
      threads: 1